server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test-product?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  data:
    elasticsearch:
      repositories:
        enabled: true
#      cluster-nodes: 127.0.0.1:9200 #es的连接地址及端口号（6版本）
#      cluster-name: elasticsearch #es集群的名称（6版本）
  elasticsearch: #7版本
    rest:
      uris: http://localhost:9200
